import 'package:team_draw/models/player.dart';
import 'package:team_draw/models/position.dart';

List<Player> playersList = [
  Player(
    name: "Ribeiro",
    principalPosition: Position.MEIO_CAMPISTA,
    secondaryPosition: Position.ATACANTE,
    overall: 10,
  ),
  Player(
    name: "Pedro",
    principalPosition: Position.LATERAL,
    secondaryPosition: Position.ATACANTE,
    tertiaryPosition: Position.DEFENSOR,
    overall: 7,
  ),
  Player(
    name: "Jodir",
    principalPosition: Position.DEFENSOR,
    secondaryPosition: Position.MEIO_CAMPISTA,
    tertiaryPosition: Position.ATACANTE,
    overall: 7,
  ),
  Player(
    name: "Rodrigo",
    principalPosition: Position.DEFENSOR,
    secondaryPosition: Position.ATACANTE,
    tertiaryPosition: Position.LATERAL,
    overall: 8,
  ),
  Player(
    name: "Helton",
    principalPosition: Position.DEFENSOR,
    secondaryPosition: Position.MEIO_CAMPISTA,
    tertiaryPosition: Position.ATACANTE,
    overall: 10,
  ),
  Player(
    name: "Cris",
    principalPosition: Position.MEIO_CAMPISTA,
    secondaryPosition: Position.ATACANTE,
    tertiaryPosition: Position.DEFENSOR,
    overall: 9,
  ),
  Player(
    name: "Cleber",
    principalPosition: Position.DEFENSOR,
    secondaryPosition: Position.MEIO_CAMPISTA,
    tertiaryPosition: Position.ATACANTE,
    overall: 9,
  ),
  Player(
    name: "Helder",
    principalPosition: Position.ATACANTE,
    secondaryPosition: Position.DEFENSOR,
    tertiaryPosition: Position.MEIO_CAMPISTA,
    overall: 7,
  ),
  Player(
    name: "Douglas",
    principalPosition: Position.LATERAL,
    secondaryPosition: Position.ATACANTE,
    tertiaryPosition: Position.DEFENSOR,
    overall: 6,
  ),
  Player(
    name: "Sid",
    principalPosition: Position.ATACANTE,
    overall: 5,
  ),
  Player(
    name: "Neny",
    principalPosition: Position.ATACANTE,
    secondaryPosition: Position.LATERAL,
    tertiaryPosition: Position.DEFENSOR,
    overall: 7,
  ),
  Player(
    name: "Diego",
    principalPosition: Position.ATACANTE,
    secondaryPosition: Position.DEFENSOR,
    tertiaryPosition: Position.MEIO_CAMPISTA,
    overall: 10,
  ),
  Player(
    name: "Galdino",
    principalPosition: Position.GOLEIRO,
    overall: 10,
  ),
  Player(
    name: "Bruno",
    principalPosition: Position.MEIO_CAMPISTA,
    secondaryPosition: Position.ATACANTE,
    tertiaryPosition: Position.DEFENSOR,
    overall: 9,
  ),
  Player(
    name: "Guilherme",
    principalPosition: Position.ATACANTE,
    secondaryPosition: Position.LATERAL,
    tertiaryPosition: Position.DEFENSOR,
    overall: 6,
  ),
];
